# Generated by Django 2.2.10 on 2020-04-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191209_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lecturer',
        ),
    ]
