# Generated by Django 3.0.5 on 2020-04-20 13:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.upload_location),
        ),
    ]
