# Generated by Django 3.0.5 on 2020-05-01 17:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, upload_to=users.models.upload_location),
        ),
    ]
