# Generated by Django 3.0.5 on 2020-05-03 12:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200501_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='default.png', upload_to=users.models.upload_location),
        ),
    ]
