# Generated by Django 2.2.6 on 2019-12-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='member',
            new_name='members',
        ),
    ]
